# Generated by Django 3.1.3 on 2020-11-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_auto_20201113_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python',
            new_name='Report',
        ),
    ]
