# Generated by Django 3.1.3 on 2020-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0004_report_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
