# Generated by Django 3.1.3 on 2020-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0005_report_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='short_description',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
