# Generated by Django 3.1.3 on 2020-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0006_report_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.FileField(upload_to='files'),
        ),
    ]
