# Generated by Django 3.1.3 on 2020-12-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0007_auto_20201207_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='file',
        ),
    ]
