# Generated by Django 3.1.3 on 2020-12-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0011_auto_20201211_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='added_by',
        ),
    ]
